DROP DATABASE IF EXISTS parcelDelivery;
CREATE DATABASE parcelDelivery;
USE parcelDelivery;

CREATE TABLE `user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `street_address` VARCHAR(45) NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `parcel` (
  `id_parcel` int NOT NULL AUTO_INCREMENT,
  `id_user` int DEFAULT NULL,
  `reciever_name` varchar(45) NOT NULL,
  `reciever_telephone` varchar(45) NOT NULL,
  `reciever_street_address` varchar(45) NOT NULL,
  `reciever_postal_code` char(6) NOT NULL,
  `reciever_city` varchar(45) NOT NULL,
  `sender_name` varchar(45) NOT NULL,
  `sender_telephone` varchar(45) DEFAULT NULL,
  `sender_street_address` varchar(45) DEFAULT NULL,
  `sender_postal_code` char(5) DEFAULT NULL,
  `sender_city` varchar(45) DEFAULT NULL,
  `parcel_dropoff_date` date DEFAULT NULL,
  `parcel_readyforpickup_date` date DEFAULT NULL,
  `parcel_pickup_date` date DEFAULT NULL,
  `parcel_last_pickup_date` date DEFAULT NULL,
  `pin_code` int DEFAULT NULL,
  `status` ENUM('ready_to_deliver', 'parcel_at_dropoff_locker', 'parcel_in_transportation', 'parcel_in_pickup_locker', 'reciever_recieved_parcel') NOT NULL,
  `desired_dropoff_locker` tinyint NOT NULL,
  `desired_pickup_locker` tinyint NOT NULL,
  `alternative_pickup_locker` tinyint DEFAULT NULL,
  `parcel_height` float NOT NULL,
  `parcel_width` float NOT NULL,
  `parcel_depth` float NOT NULL,
  `parcel_mass` float NOT NULL,
  `receiver_email`  VARCHAR(45) NOT NULL,
  `sender_email` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id_parcel`),
  KEY `id_user_idx` (`id_user`),
  CONSTRAINT `id_user` FOREIGN KEY (`id_user`) REFERENCES `user` (`id_user`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `locker` (
  `id_cabinet` tinyint NOT NULL AUTO_INCREMENT,
  `locker_number` tinyint NOT NULL,
  `cabinet_number` tinyint NOT NULL,
  `cabinet_status` ENUM('free', 'has_dropoff_parcel', 'has_pickup_parcel') NOT NULL,
  `parcel_id` int DEFAULT NULL,
  PRIMARY KEY (`id_cabinet`),
  UNIQUE KEY `id_cabinet_UNIQUE` (`id_cabinet`),
  KEY `parcel_id_idx` (`parcel_id`),
  CONSTRAINT `parcel_id` FOREIGN KEY (`parcel_id`) REFERENCES `parcel` (`id_parcel`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


/* Values for status:
Values for cabinet status:
free - cabinet is empty
has_dropoff_parcel - cabinet has a parcel to collect by driver
has_pickup_parcel - cabinet has a parcel to pickup by a customer
*/

ALTER TABLE `parcel`
ADD COLUMN receiver_email VARCHAR(45) NOT NULL,
ADD COLUMN sender_email VARCHAR(45) DEFAULT NULL;

INSERT INTO locker (locker_number, cabinet_number, cabinet_status, parcel_id) VALUES
(1, 1, 'free', NULL),
(1, 2, 'free', NULL),
(1, 3, 'free', NULL),
(1, 4, 'free', NULL),
(1, 5, 'free', NULL),
(1, 6, 'free', NULL),
(1, 7, 'free', NULL),
(1, 8, 'free', NULL),
(1, 9, 'free', NULL),
(1, 10, 'free', NULL),
(1, 11, 'free', NULL),
(1, 12, 'free', NULL),
(1, 13, 'free', NULL),
(1, 14, 'free', NULL),
(1, 15, 'free', NULL),
(2, 1, 'free', NULL),
(2, 2, 'free', NULL),
(2, 3, 'free', NULL),
(2, 4, 'free', NULL),
(2, 5, 'free', NULL),
(2, 6, 'free', NULL),
(2, 7, 'free', NULL),
(2, 8, 'free', NULL),
(2, 9, 'free', NULL),
(2, 10, 'free', NULL),
(2, 11, 'free', NULL),
(2, 12, 'free', NULL),
(2, 13, 'free', NULL),
(2, 14, 'free', NULL),
(2, 15, 'free', NULL),
(3, 1, 'free', NULL),
(3, 2, 'free', NULL),
(3, 3, 'free', NULL),
(3, 4, 'free', NULL),
(3, 5, 'free', NULL),
(3, 6, 'free', NULL),
(3, 7, 'free', NULL),
(3, 8, 'free', NULL),
(3, 9, 'free', NULL),
(3, 10, 'free', NULL),
(3, 11, 'free', NULL),
(3, 12, 'free', NULL),
(3, 13, 'free', NULL),
(3, 14, 'free', NULL),
(3, 15, 'free', NULL),
(4, 1, 'free', NULL),
(4, 2, 'free', NULL),
(4, 3, 'free', NULL),
(4, 4, 'free', NULL),
(4, 5, 'free', NULL),
(4, 6, 'free', NULL),
(4, 7, 'free', NULL),
(4, 8, 'free', NULL),
(4, 9, 'free', NULL),
(4, 10, 'free', NULL),
(4, 11, 'free', NULL),
(4, 12, 'free', NULL),
(4, 13, 'free', NULL),
(4, 14, 'free', NULL),
(4, 15, 'free', NULL),
(5, 1, 'free', NULL),
(5, 2, 'free', NULL),
(5, 3, 'free', NULL),
(5, 4, 'free', NULL),
(5, 5, 'free', NULL),
(5, 6, 'free', NULL),
(5, 7, 'free', NULL),
(5, 8, 'free', NULL),
(5, 9, 'free', NULL),
(5, 10, 'free', NULL),
(5, 11, 'free', NULL),
(5, 12, 'free', NULL),
(5, 13, 'free', NULL),
(5, 14, 'free', NULL),
(5, 15, 'free', NULL);
